Enhance error handling in exit paths: replace direct `cd` failures with explicit checks, add descriptive error messages, rename `exit_flatsync` to `exit_flatsync_grace`, and update all call sites

diff --git a/app/import/exit_flatsync b/app/import/exit_flatsync
--- a/app/import/exit_flatsync
+++ b/app/import/exit_flatsync
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 
-exit_flatsync() {
+exit_flatsync_grace() {
     if [ "$NO_TODO" -lt 2 ]; then
         for old_items in "$FLATSYNC_CACHE"/*; do
             shred -u "$old_items"
         done
     fi
     ###
-    cd "$FLATSYNC_GIT" || rm /run/user/$UID/flatsync.lock && exit 1
+    if ! cd "$FLATSYNC_GIT"; then
+        echo "Error! Flatsync git repository not found at: \n$FLATSYNC_GIT\nExiting"
+        rm /run/user/$UID/flatsync.lock && exit 1
+    fi
 
     flatpak list --columns=application --app |
         tee -p remote_flatpaks &>/dev/null
diff --git a/app/import/flags_handling b/app/import/flags_handling
--- a/app/import/flags_handling
+++ b/app/import/flags_handling
@@ -108,7 +108,10 @@ EOF
             ###
             UPDATE_LUD=${UPDATE_LUD:-"true"}
             if [ "$UPDATE_LUD" = true ]; then
-                cd "$FLATSYNC_GIT" || exit
+                if ! cd "$FLATSYNC_GIT"; then
+                    echo "Error! Flatsync git repository not found at: \n$FLATSYNC_GIT\nExiting"
+                    rm /run/user/$UID/flatsync.lock && exit 1
+                fi
                 LUD_FLATSYNC_ID=$(printf "%s" "$(cat /usr/share/flatsync/flatsync-id)")
                 printf "%s\n%s" "$(cat /etc/hostname)" "$LUD_FLATSYNC_ID" 1>last_updated_device
                 git add .
diff --git a/flatsync b/flatsync
--- a/flatsync
+++ b/flatsync
@@ -67,7 +67,10 @@ source "$FLATSYNC_IMPORTS"/git_config_default_values
 check-dir_git
 check-dir_ssh
 
-cd "$FLATSYNC_GIT" || rm /run/user/$UID/flatsync.lock && exit
+if ! cd "$FLATSYNC_GIT"; then
+    echo "Error! Flatsync git repository not found at: \n$FLATSYNC_GIT\nExiting"
+    rm /run/user/$UID/flatsync.lock && exit 1
+fi
 
 if [ -d "$FLATSYNC_GIT"/.git ]; then
     ssh-add -q "$FLATSYNC_SSH"/flatsync_key 2>/dev/null
@@ -218,7 +221,7 @@ set +e +u +o pipefail
 if [ -e "$FLATSYNC_GIT"/last_updated_device ] && { [ "$LUD_HOSTNAME" = "$(cat /etc/hostname)" ] && [ "$LUD_FLATSYNC_ID" = "$FLATSYNC_ID" ]; }; then
 
     NO_TODO=2
-    exit_flatsync
+    exit_flatsync_grace
 
 else
 
@@ -396,4 +399,4 @@ elif [ -d "$FLATSYNC_GIT"/overrides ] && ! [ -d "$HOME"/.local/share/flatpak/ove
 fi
 ############
 
-exit_flatsync
+exit_flatsync_grace
